name: cell_viewer
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-image
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - napari
  - nbdime
  - numpy
  - pandas
  - pandas-profiling
  - pip
  - pyjanitor
  - pylint
  - pyqt
  - python=3.9.1
  - qt>=5.12.3
  - read-roi
  - scikit-learn
  - seaborn
  - shapely
  - snakemake
  - statsmodels
  - pip:
      - pyhere